<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wfqbe"
 *
 * Auto generated by Extension Builder 2017-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'DB Integration',
	'description' => 'This extension allows to generate queries (with a little sql knowledge), search forms and insert forms to generic databases through a wizard. The results visualization is template-based and fully configurable via TS. The extension uses ADOdb and supports XAJAX.',
	'category' => 'plugin',
	'author' => 'Davide Menegon, Mauro Lorenzutti, David Bruchmann',
	'author_email' => 'menedav@libero.it, mauro.lorenzutti@webformat.com, david.bruchmann@gmail.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'adodb' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);